### ISSUE TITLE
secure aggregation failure

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#1002]
Usng v5.1.0 secure aggregation fails under the following circumstances:
- running in docker/vpn mode
- 3 nodes
- using a modified `general-tutorial-secagg.ipynb` (1) without `batch_maxnum` (2) with 150 rounds (3) no breakpoint, added `tensorboard=True`

Failure occured (4 runs) between round 65 and 77

```
2024-02-20 12:31:53,384 fedbiomed INFO - INFO NODE NODE_0274b913-90d9-4fc9-8dc3-038c60e88859
      MESSAGE: Encryption is completed!
-----------------------------------------------------------------
2024-02-20 12:31:53,941 fedbiomed INFO - Nodes that successfully reply in round 73 ['NODE_307b892a-2d4c-444b-ae70-d8043f0a3d90', 'NODE_1ae95fca-69b5-4171-8b53-12b14a4cf660', 'NODE_0274b913-90d9-4fc9-8dc3-038c60e88859']
2024-02-20 12:31:53,943 fedbiomed INFO - Validating secure aggregation results...
2024-02-20 12:31:53,948 fedbiomed INFO - Aggregating 3 parameters from 3 nodes.
2024-02-20 12:31:53,949 fedbiomed DEBUG - Aggregation is completed in 0.01 seconds.
2024-02-20 12:31:53,950 fedbiomed INFO - Validation is completed.
2024-02-20 12:31:53,951 fedbiomed INFO - Aggregating encrypted parameters. This process may take some time depending on model size.
2024-02-20 12:34:09,047 fedbiomed INFO - Aggregating 3 parameters from 3 nodes.
2024-02-20 12:34:09,538 fedbiomed DEBUG - Aggregation is completed in 135.53 seconds.
--------------------
Fed-BioMed researcher stopped due to unknown error:
shape '[10]' is invalid for input of size 9
More details in the backtrace extract below
--------------------
Traceback (most recent call last):
  File "/fedbiomed/fedbiomed/researcher/experiment.py", line 76, in payload
    ret = function(*args, **kwargs)
  File "/fedbiomed/fedbiomed/researcher/experiment.py", line 1509, in run_once
    self._job.training_plan._model.unflatten(flatten_params)
  File "/fedbiomed/fedbiomed/common/models/_torch.py", line 116, in unflatten
    torch.nn.utils.vector_to_parameters(vector, model.parameters())
  File "/home/fedbiodev/.conda/envs/fedbiomed-researcher/lib/python3.10/site-packages/torch/nn/utils/convert_parameters.py", line 51, in vector_to_parameters
    param.data = vec[pointer:pointer + num_param].view_as(param).data
RuntimeError: shape '[10]' is invalid for input of size 9
--------------------

2024-02-20 12:34:09,753 fedbiomed CRITICAL - Fed-BioMed stopped due to unknown error:
shape '[10]' is invalid for input of size 9
2024-02-20 12:34:33,818 fedbiomed DEBUG - Node: NODE_1ae95fca-69b5-4171-8b53-12b14a4cf660 polling for the tasks
2024-02-20 12:44:16,872 fedbiomed DEBUG - Node: NODE_307b892a-2d4c-444b-ae70-d8043f0a3d90 polling for the tasks
2024-02-20 12:50:00,009 fedbiomed DEBUG - Node: NODE_0274b913-90d9-4fc9-8dc3-038c60e88859 polling for the tasks

```

If comparing the received params unflattened with the model geometry:

```
vector = torch.as_tensor(flatten_params).type(torch.DoubleTensor)
len(vector)
```
... gives 1199881

```
params = torch.nn.utils.parameters_to_vector(
            exp._job.training_plan._model.model.parameters()
        ).tolist()
len(params)
```
... gives 1199882

**Comment by mvesin** [comment]
Additional tests:
- in  different setups (VPN/container on different machines, dev setup on one laptop)
- 2 or 3 nodes for each
- same issue always happens, between round 55 and 100

**Comment by rtaiello** [comment]
@mvesin can we save the vector (torch tesnor) at each round (just for the most recenet) for each nodes?

**Comment by mvesin** [comment]
Thanks @rtaiello for the joint investigation !

The issue was found to be in the `VES._debatch()` in the case where the leading encoded value of an encoded parameter is 0 (thus `- CLIPPING_RANGE` with the current quantization). In this case this encoded value is skipped and one decoded parameter is lost.

This is a rare case which explains this wasn't detected until a long run.

**Comment by mvesin** [comment]
Nice, the fix was tested
- with 2 different setups (one on local laptop, one with docker+VPN on different machines)
- each setup with `general-tutorial-secagg.ipynb` notebook + 3 nodes
- ran 150 rounds (no `batch_maxnum`)

Both tests completed successfully.
