### ISSUE TITLE
convergence incorrect on macosx-m1

### ISSUE THREAD

**Issue by ErwanDemairy** [fedbiomed/fedbiomed#807]
The following test is failing randomly, but seems to appear more often on macosx-m1 than on other platforms (no such report found for ubuntu or fedora):
```
Traceback (most recent call last):
  File "/Users/ci/.conda/envs/fedbiomed-researcher/lib/python3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
  File "/Users/ci/actions-runner/_work/fedbiomed/fedbiomed/tests/test_round.py", line 152, in test_round_01_run_model_training_normal_case
    self.assertLess(
AssertionError: 1.150049916999997 not less than 1.1
```

**Comment by srcansiz** [comment]
Hi @ErwanDemairy, 
I guess this problem is not existing anymore. I am closing the issue
