### ISSUE TITLE
`NameError` when declaring Experiment

### ISSUE THREAD

**Issue by sharkovsky** [fedbiomed/fedbiomed#864]
A  `NameError` can occur when calling the Experiment constructor because of the following chain of events:
1) call Experiment init
2) this calls Job init
3) this instantiates a TrainingPlan, and calls `post_init`

When point 3 is reached, the `NameError` arises because the dependencies of the training plan have not been correctly imported by the Job init. Indeed, in other cases (for example, on the node side in Round) we import the training plan file before instantiating the training plan class, which solves the problem. 

A small example that reproduces the error is given below

```python
from fedbiomed.common.training_plans import TorchTrainingPlan
from fedbiomed.common.logger import logger
from fedbiomed.common.data import DataManager, MedicalFolderDataset
from fedbiomed.researcher.experiment import Experiment
from fedbiomed.researcher.aggregators.fedavg import FedAverage

class UNetTrainingPlan(TorchTrainingPlan):

    def init_model(self, model_args):
        model = DenseNet(spatial_dims=1,in_channels=1,out_channels=1)
        return model


    def init_optimizer(self):
        optimizer = AdamW(self.model().parameters())
        return optimizer

    def init_dependencies(self):
        # Here we define the custom dependencies that will be needed by our custom Dataloader
        deps = ['from monai.networks.nets import DenseNet',
                "import torch.nn as nn",
                'import torch.nn.functional as F',
                'from torch.optim import AdamW',]
        return deps

    def training_data(self):
    # The training_data creates the Dataloader to be used for training in the general class Torchnn of fedbiomed
        dataset = MedicalFolderDataset(
            root=self.dataset_path,
            data_modalities='T1',
            target_modalities='label',
            transform=None,
            target_transform=None,
            demographics_transform=None)
        loader_arguments = {'shuffle': True}
        return DataManager(dataset, **loader_arguments)


    def training_step(self, data, target):
        return 0

tags =  ['ixi-train']

exp = Experiment(tags=tags,
                 model_args={},
                 training_plan_class=UNetTrainingPlan,
                 training_args={},
                 round_limit=1,
                 aggregator=FedAverage()
                )
```

Which leads to the error
```bash
--------------------
Fed-BioMed researcher stopped due to unknown error:
name 'DenseNet' is not defined
More details in the backtrace extract below
--------------------
Traceback (most recent call last):
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/researcher/experiment.py", line 72, in payload
    ret = function(*args, **kwargs)
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/researcher/experiment.py", line 278, in __init__
    self.set_job()
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/researcher/experiment.py", line 1430, in set_job
    self._job = Job(reqs=self._reqs,
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/researcher/job.py", line 145, in __init__
    self._training_plan.post_init(model_args={} if self._model_args is None else self._model_args,
  File "/Users/fcremone/dev/fedbiomed/fedbiomed/common/training_plans/_torchnn.py", line 157, in post_init
    self._configure_model_and_optimizer()
NameError: name 'DenseNet' is not defined
--------------------
```

**Comment by mvesin** [comment]
IMHO this is not a bug: the documented way of writing a training plan (see all sample notebooks) is to have the import both on the researcher (in the cell, outside of TrainingPlan class) and on the node via `init_dependencies()`

But new version is clearly an enhancement to simplify the data scientist interface !
