### ISSUE TITLE
Tkinter crash when loading datasets in non-interactive mode

### ISSUE THREAD

**Issue by sharkovsky** [fedbiomed/fedbiomed#978]
In Fed-BioMed v5.0.0, when loading a dataset (e.g. of medical-folder type) in a *non-interactive* way, the process fails when the file selector should be displayed with the following error message
```bash
Traceback (most recent call last):
  File "/home/fedbiodev/.conda/envs/fedbiomed-node/lib/python3.10/tkinter/messagebox.py", line 76, in _show
    res = Message(**options).show()
  File "/home/fedbiodev/.conda/envs/fedbiomed-node/lib/python3.10/tkinter/commondialog.py", line 42, in show
    master = _get_temp_root()
  File "/home/fedbiodev/.conda/envs/fedbiomed-node/lib/python3.10/tkinter/__init__.py", line 306, in _get_temp_root
    raise RuntimeError("No master specified and tkinter is "
RuntimeError: No master specified and tkinter is configured to not support default root
```

**Comment by sharkovsky** [comment]
The issue is in [line 69](https://github.com/fedbiomed/fedbiomed/blob/851e95f1bf1653ee168bbb0e28930a3769fcc53f/fedbiomed/node/cli_utils/_io.py#L69) of `fedbiomed/node/cli_utils/_io.py`: we only catch `ModuleNotFoundError, _tkinter.TclError` but in this case a `RuntimeError` is raised.

**Comment by mvesin** [comment]
Can you give details about a command triggering the issue to be able to reproduce / test the fix ?
