### ISSUE TITLE
multiple stability issues with gRPC communications

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#980]
To be detailed

**Comment by mvesin** [comment]
Case 1 output on node:
```
2024-01-25 12:57:28,661 fedbiomed DEBUG - Train Epoch: 1 | Iteration 1240/1250 | Samples 59520/60000 (99%) Loss: 0.003535
2024-01-25 12:57:28,775 fedbiomed DEBUG - Train Epoch: 1 | Iteration 1250/1250 | Samples 60000/60000 (100%) Loss: 0.014251
2024-01-25 12:57:28,786 fedbiomed WARNING - save_state method of optimizer not implemented, cannot save optimizer status
2024-01-25 12:57:28,787 fedbiomed WARNING - Unable to save optimizer state of type <class 'fedbiomed.common.optimizers.generic_optimizers.NativeTorchOptimizer'>. Skipping...
2024-01-25 12:57:28,790 fedbiomed DEBUG - Node state has been partially saved into the Database
2024-01-25 12:57:28,922 fedbiomed DEBUG - Sending new task request to researcher
2024-01-25 12:57:28,925 fedbiomed CRITICAL - An exception raised by running tasks within GrpcClients. This will stop gRPC client. The exception: FedbiomedCommunicationError. Error message: ErrorNumbers.FB628: Sender has stopped due to unknown reason: RPC already finished.
2024-01-25 12:57:28,925 - Not able to send log message to remote party
coroutine 'GrpcAsyncTaskController.send' was never awaited
2024-01-25 12:57:28,925 fedbiomed INFO - Node is stopped!
2024-01-25 12:57:28,925 - Not able to send log message to remote party
```

Case 2 output on node:
```
2024-01-25 13:16:19,808 fedbiomed DEBUG - Train Epoch: 1 | Iteration 1130/1250 | Samples 54240/60000 (90%) Loss: 0.041607
2024-01-25 13:16:19,875 fedbiomed DEBUG - Train Epoch: 1 | Iteration 1140/1250 | Samples 54720/60000 (91%) Loss: 0.002722
2024-01-25 13:16:19,942 fedbiomed DEBUG - Train Epoch: 1 | Iteration 1150/1250 | Samples 55200/60000 (92%) Loss: 0.000723
2024-01-25 13:16:20,008 fedbiomed DEBUG - Train Epoch: 1 | Iteration 1160/1250 | Samples 55680/60000 (93%) Loss: 0.201752
2024-01-25 13:16:20,075 fedbiomed DEBUG - Train Epoch: 1 | Iteration 1170/1250 | Samples 56160/60000 (94%) Loss: 0.010456
2024-01-25 13:16:20,095 fedbiomed DEBUG - Sending new task request to researcher
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/fedbiomed/fedbiomed/transport/client.py", line 473, in _listen
    await self._get(callback)
  File "/fedbiomed/fedbiomed/transport/client.py", line 519, in _get
    await msg["stub"](msg["message"])
  File "/home/fedbiomed/.conda/envs/fedbiomed-node/lib/python3.10/site-packages/grpc/aio/_call.py", line 304, in __await__
    raise asyncio.CancelledError()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fedbiomed/fedbiomed/transport/controller.py", line 80, in start
    await asyncio.gather(*tasks)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fedbiomed/fedbiomed/transport/controller.py", line 150, in _run
    asyncio.run(super().start(), debug=self._debug)
  File "/home/fedbiomed/.conda/envs/fedbiomed-node/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/fedbiomed/.conda/envs/fedbiomed-node/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
2024-01-25 13:16:20,145 fedbiomed DEBUG - Train Epoch: 1 | Iteration 1180/1250 | Samples 56640/60000 (94%) Loss: 0.096461
coroutine 'GrpcAsyncTaskController.send' was never awaited
2024-01-25 13:16:20,145 fedbiomed ERROR - FB601: message error: Cannot send error message: Event loop is closed
2024-01-25 13:16:20,145 - Not able to send log message to remote party
coroutine 'GrpcAsyncTaskController.send' was never awaited
coroutine 'GrpcAsyncTaskController.send' was never awaited
2024-01-25 13:16:20,145 fedbiomed CRITICAL - Node stopped.
2024-01-25 13:16:20,145 - Not able to send log message to remote party
coroutine 'GrpcAsyncTaskController.send' was never awaited
To stop press Ctrl + C.
```

Case 3 : no log trace

Case 4 output on node:
```
2024-01-26 07:51:29,046 fedbiomed DEBUG - Train Epoch: 1 | Iteration 260/1250 | Samples 12480/60000 (21%) Loss: 0.000296
2024-01-26 07:51:29,410 fedbiomed DEBUG - Train Epoch: 1 | Iteration 270/1250 | Samples 12960/60000 (22%) Loss: 0.058603
2024-01-26 07:51:29,782 fedbiomed DEBUG - Train Epoch: 1 | Iteration 280/1250 | Samples 13440/60000 (22%) Loss: 0.011017
2024-01-26 07:51:30,150 fedbiomed DEBUG - Train Epoch: 1 | Iteration 290/1250 | Samples 13920/60000 (23%) Loss: 0.055386
2024-01-26 07:51:30,152 fedbiomed DEBUG - Sending new task request to researcher
2024-01-26 07:51:30,153 fedbiomed CRITICAL - An exception raised by running tasks within GrpcClients. This will stop gRPC client. The exception: FedbiomedCommunicationError. Error message: ErrorNumbers.FB628: Sender has stopped due to unknown reason: Channel is closed.
2024-01-26 07:51:30,153 - Not able to send log message to remote party
coroutine 'GrpcAsyncTaskController.send' was never awaited
2024-01-26 07:51:30,153 fedbiomed INFO - Node is stopped!
2024-01-26 07:51:30,153 - Not able to send log message to remote party
2024-01-26 07:51:30,154 fedbiomed INFO - Cannot send error message to researcher (node not initialized yet)
2024-01-26 07:51:30,154 - Not able to send log message to remote party
2024-01-26 07:51:30,154 fedbiomed INFO - Node stopped in signal_handler, probably node exit on error or user decision (Ctrl C)
2024-01-26 07:51:30,154 - Not able to send log message to remote party
```

**Comment by srcansiz** [comment]
Please see the issue #981 regarding the error `Channel is closed` and the problem causes this issue.
